apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-app
  labels: 
    app: product-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app : product-service-app
  template:
    metadata:
      labels:
        app: product-service-app
    spec:
      containers:
      - name: product-service-app
        image: ghidiom/webstore-product:1.2
        imagePullPolicy: Always
        env:
          - name: PORT 
            value: "8080"
          - name: KAFKA          
            valueFrom: 
              configMapKeyRef:
                name: e-commerce-app-config
                key: kafka-address
          - name: MONGO_URL
            value: open-mongo-db-server2-mongodb
          - name: MONGO_PORT
            value: "27017"
          - name: DB_NAME
            value: SA-Project-Product
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: e-commerce-app-secret
                key: db-user-username
          - name: DB_PASSWORD
            value: root         
        ports:
          - containerPort: 8080
          
---

kind: Service
apiVersion: v1
metadata:
  name:  product-service-svc
spec:
  selector:
    app:  product-service-app
  ports:
  - port:  8080
    targetPort:  8080